# Streamlit Secrets for Local Development
# This file is not committed to GitHub (.gitignore)

[auth]
common_password_hash = "9af8e589e496a744e10a0eb1013a767976bb63e2f39dbb32c4e40b81506f5e8d"
internal_domains = ["zuelligpharma.com"]

# API Keys
GENAI_API_KEY = "AIzaSyDUaVhDdxQQGSoudbESVv6PRpZrBW7aT_0"
NAVER_CLIENT_ID = "2jyhekkhkZCQNyh8tVKb"
NAVER_CLIENT_SECRET = "IMqTRsZRvq"
